[build]
builder = "nixpacks"

[[services]]
name = "api"
source = "api"
[services.build]
buildCommand = "pnpm install && pnpm run build"
[services.deploy]
startCommand = "pnpm run start:prod"
healthcheckPath = "/api/users"
healthcheckTimeout = 30

[[services]]
name = "web"
source = "web"
[services.build]
buildCommand = "pnpm install && pnpm run build"
[services.deploy]
startCommand = "pnpm dlx serve dist -p ${PORT:-3000} -s"
